language: java
before_install:
  # download the latest android sdk and unzip
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar -zxf android-sdk_r21.0.1-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  # use ~/builds/[Github username]/[project]/android-sdk-linux
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --no-ui --obsolete --force
install:
  - mvn install -DskipTests=true
notifications:
  hipchat:
    - secure: "SYNsoAV2/tvC7l4IdJxBHjczthLuuOCJ3zruu55MN3EYomf25tlRed8msuVU\nv7n8sYWcPjiUI5lbHzQTKU0PT1+arlBMwRhPMG719ID3BcmufXqVys4yzn+K\nAL3YaDONClJRaNbuaqVpz7l97jvsN/VGYbKCGvymiGf6sKu6T4Y="
